### ISSUE TITLE
Problem Using Update Payment

### ISSUE THREAD

**Issue by geraldogebler** [mercadopago/sdk-python#45]
Im trying to use the Payment Update to change the external_reference. But it gives me an error:

code:
`
def set_order_value(p_pgto_id, p_key, p_value):
    
    import mercadopago

    sdk = mercadopago.SDK("MY_TOKEN")

    payment_data = {
        "external_reference": "100",
    }
    result = sdk.payment().update(p_pgto_id, payment_data)
    print(result)`

output:
`{'status': 400, 'response': {'message': 'Unauthorized product_id', 'error': 'bad_request', 'status': 400, 'cause': [{'code': 9100, 'description': 'Unauthorized product_id', 'data': None}]}}`

Im I missing something?`

output:
`{'status': 400, 'response': {'message': 'Unauthorized product_id', 'error': 'bad_request', 'status': 400, 'cause': [{'code': 9100, 'description': 'Unauthorized product_id', 'data': None}]}}`

Im I missing something?

**Comment by mrossafa** [comment]
Hi @geraldogebler,

It is not possible to change this attribute.  Do you have some specific reason for changing the external_reference?

Thank you for contacting us!

**Comment by geraldogebler** [comment]
Yes I do. It is in the documentation of update, which could be updated to
get some references with my application.

Em qua, 5 de mai de 2021 16:47, Mario Rossafa ***@***.***>
escreveu:

**Comment by geraldogebler** [comment]
Yeah... I'm in touch with them... It seems the API is outdated in comparission with the mercadopago documentation. Well, thanks anyways 😉
