### ISSUE TITLE
"No module named 'requests'" after importing mercadopago.SDK

### ISSUE THREAD

**Issue by ldelelis** [mercadopago/sdk-python#46]
**Describe the bug**
Mercadopago seems to depend on `requests`, but such dependency is not listed anywhere in the repository

**To Reproduce**

1. Create a new virtualenv: `python3 -m venv testrequests`
2. Activate said virtualenv: `source testrequests/bin/activate`
3. Install the mercadopago package: `pip3 install mercadopago`
4. Open a python shell: `python3`
5. Attempt to import mercadopago: `import mercadopago`

Resulting error: https://linkode.org/#IlUSQI3ud16EuNfHWP7Xw6

- Test case to reproduce the bug.  Try to reproduce in the latest version.
- Code sample that fails

**Expected behavior**
The module is imported without issues

**Environment (please complete the following information):**

- OS: Windows 10
- Python version: 3.8.5
- SDK version: 2.0.6

**Comment by delias-silva** [comment]
Hello @ldelelis, thanks for the report!

We will fix the problem and release a new version soon.
